# a=int(input('a='))
# b=int(input('b='))
# c=int(input('c='))
# d=int(input('d='))
# print('Tong =',a+b+c+d)
# print('Trung binh cong =',round((a+b+c+d)/4))
a=int(input('a='))
b=int(input('b='))
c=int(input('c='))
d=int(input('d='))
print('Tong = ' + str(a+b+c+d))
print('Trung binh cong = ' + str((a+b+c+d)//4))